//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xdwlEntities : DbContext
    {
        public xdwlEntities()
            : base("name=xdwlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAbout> tAbout { get; set; }
        public virtual DbSet<tArticle> tArticle { get; set; }
        public virtual DbSet<tArticleType> tArticleType { get; set; }
        public virtual DbSet<tGuestBook> tGuestBook { get; set; }
        public virtual DbSet<tLink> tLink { get; set; }
        public virtual DbSet<tLinkType> tLinkType { get; set; }
        public virtual DbSet<tMenu> tMenu { get; set; }
        public virtual DbSet<tMenuGroup> tMenuGroup { get; set; }
        public virtual DbSet<tPicture> tPicture { get; set; }
        public virtual DbSet<tPictureType> tPictureType { get; set; }
        public virtual DbSet<tRole> tRole { get; set; }
        public virtual DbSet<tSet> tSet { get; set; }
        public virtual DbSet<tUsers> tUsers { get; set; }
        public virtual DbSet<tRoleMenu> tRoleMenu { get; set; }
    }
}
