//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAbout
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AboutContent { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Editor { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<int> Click { get; set; }
        public string Remark { get; set; }
        public string FengMian { get; set; }
        public Nullable<int> IsEnable { get; set; }
    }
}
