//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMenuGroup
    {
        public int menuGroupCode { get; set; }
        public string menuGroupName { get; set; }
        public Nullable<int> parentCode { get; set; }
        public string menuGroupUrl { get; set; }
        public Nullable<int> seq { get; set; }
        public string target { get; set; }
        public string remark { get; set; }
    }
}
