//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMenu
    {
        public int menuCode { get; set; }
        public string menuName { get; set; }
        public string menuUrl { get; set; }
        public Nullable<int> sort { get; set; }
        public string menuType { get; set; }
        public int menuParent { get; set; }
        public string target { get; set; }
        public string rel { get; set; }
        public string fresh { get; set; }
        public string note { get; set; }
    }
}
