//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSet
    {
        public int Id { get; set; }
        public string WebName { get; set; }
        public string Copyright { get; set; }
        public string KeyWords { get; set; }
        public string Description { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string BeiAn { get; set; }
    }
}
